datasets:
  data_dir: 'data/synthetic'
  file_name: 'synthetic_dataset_linda_original_gold.json'
  test_on_subset: False # for debugging only
  num_test_data: 10
  num_synthetic_examples: 10
  synthetic_data_filename: 'data/synthetic/synthetic_dataset'
  occupations_filename: 'data/source/occupations_data.txt'
  roc_stories_filename: 'data/source/ROCStories_winter2017.csv'
  cnn_dailymails_filename: 'data/source/cnn_dailymail_train-00000-of-00003.parquet'
  vocabulary_filename: 'data/source/esl_kids_vocabulary.txt'
  top_news_agencies_filename: 'data/source/top_news_agencies.txt'
  us_news_top_universities_filename: 'data/source/us_news_top_universities.txt'
  connector: 'because' # 'because', 'so that', 'to'
  disease_symptoms_filename: 'data/disease_symptom_description_dataset.csv'
  celebrity_names_filename: 'data/celebrity_names.txt'
  natural_disasters_filename: 'data/natural_disasters.txt'
  fallacy_type: 'linda' # 'linda', 'sets'
  generate_mode: 'baseline' # 'baseline', 'control'
  linda_problem_variant: 'original' # 'original', 'variant_one', 'variant_two', 'variant_three', 'variant_four'
models:
  llm_model: 'gpt-4-turbo'  # 'gpt3.5', 'gpt-3.5-turbo' (same as gpt3.5), 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-0613',
                            # 'gpt4', 'gpt-4-turbo' (same as gpt4), 'gpt-4-0125-preview', 'gpt-4-1106-preview', 'gpt-4-0613'
                            # 'gemini', 'gemini-1.0-pro' (same as gemini), 'gemini-1.5-pro-preview-0409'
                            # 'llama', 'llama3-70b' (same as llama), 'meta-llama-3-70b-instruct' (same as llama), 'llama3-8b', 'meta-llama-3-8b-instruct' (same as llama8b),
                            # 'llama-2-70b-chat', 'llama-2-13b-chat', 'llama-2-7b-chat'
                            # 'claude', 'claude-3-opus-20240229' (same as claude), 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'
                            # 'mistral', 'mistral-large-latest' (same as mistral), 'mistral-medium-latest', 'mistral-small-latest',
                            # 'open-mixtral-8x22b', 'open-mixtral-8x7b', 'open-mistral-7b'
  gemini_credential_path: 'google-cloud-sdk/google_gemini_credential.json'
inference:
  task: 'inference' # 'inference', 'data'
  mode: 'baseline' # 'baseline', 'zs_cot', 'os', 'os_cot', 'os_bob', 'os_bob_cot', 'os_incorrect', 'os_incorrect_cot', 'fs', 'fs_cot', 'self_reflect',
                   # 'weak_control_zs_cot, 'weak_control_os_cot', 'control_zs_cot', 'control_os_cot'
  num_few_shots_exemplars: 3
  verbose: False
  num_graders: 3
  use_multi_agents: False
  print_every: 50
  output_dir: 'outputs/'
  save_output_response: True