datasets:
  data_dir: 'data'
  file_name: 'linda_problems.json'
  test_on_subset: True # for debugging only
  num_test_data: 10
models:
  llm_model: 'gpt-3.5-turbo'  # 'gpt-3.5-turbo', 'gpt-4-turbo-preview'
inference:
  verbose: False
  num_graders: 1
  use_multi_agents: False
  print_every: 50
  output_response_filename: 'outputs/response.json'
  save_output_response: True