datasets:
  data_dir: 'data'
  file_name: 'synthetic_dataset_linda_original_gold.json'
  test_on_subset: False # for debugging only
  num_test_data: 10
  num_synthetic_examples: 10
  synthetic_data_filename: 'data/synthetic_dataset'
  occupations_filename: 'data/occupations_data.txt'
  roc_stories_filename: 'data/ROCStories_winter2017.csv'
  cnn_dailymails_filename: 'data/cnn_dailymail_train-00000-of-00003.parquet'
  connector: 'because' # 'because', 'so that', 'to'
  disease_symptoms_filename: 'data/disease_symptom_description_dataset.csv'
  celebrity_names_filename: 'data/celebrity_names.txt'
  natural_disasters_filename: 'data/natural_disasters.txt'
  fallacy_type: 'linda'
  generate_mode: 'baseline' # 'baseline', 'control'
  linda_problem_variant: 'original' # 'original', 'variant_one', 'variant_two', 'variant_three', 'variant_four'
models:
  llm_model: 'gpt-4-turbo'  # 'gpt3.5', 'gpt-3.5-turbo' (same as gpt3.5), 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-0613',
                            # 'gpt4', 'gpt-4-turbo' (same as gpt4), 'gpt-4-0125-preview', 'gpt-4-1106-preview', 'gpt-4-0613'
                            # 'gemini', 'gemini-1.0-pro' (same as gemini), 'gemini-1.5-pro-preview-0409'
  gemini_credential_path: 'google-cloud-sdk/google_gemini_credential.json'
inference:
  task: 'inference' # 'inference', 'data'
  mode: 'baseline' # 'baseline', 'zs_cot', 'os', 'os_cot', 'os_bob', 'os_bob_cot', 'os_incorrect', 'os_incorrect_cot', 'fs', 'fs_cot', 'self_reflect',
                   #'weak_control_zs_cot, 'weak_control_os_cot', 'control_zs_cot', 'control_os_cot'
  num_few_shots_exemplars: 3
  verbose: False
  num_graders: 3
  use_multi_agents: False
  print_every: 50
  output_dir: 'outputs/'
  save_output_response: True