datasets:
  data_dir: 'data'
  file_name: 'linda_problems.json'
  test_on_subset: True # for debugging only
  num_test_data: 10
  num_synthetic_examples: 10
  synthetic_data_filename: 'data/synthetic_dataset'
  occupations_filename: 'data/occupations_data.txt'
  roc_stories_filename: 'data/ROCStories_winter2017.csv'
  cnn_dailymails_filename: 'data/cnn_dailymail_train-00000-of-00003.parquet'
  connector: 'because' # 'because', 'so that', 'to'
  disease_symptoms_filename: 'data/disease_symptom_description_dataset.csv'
  celebrity_names_filename: 'data/celebrity_names.txt'
  fallacy_type: 'linda'
  generate_mode: 'baseline' # 'baseline', 'control'
  linda_problem_variant: 'original' # 'original', 'variant_one', 'variant_two'
models:
  llm_model: 'gpt-3.5-turbo'  # 'gpt-3.5-turbo', 'gpt-4-turbo-preview'
  credential_path: 'google-cloud-sdk/google_gemini_credential.json'
inference:
  task: 'inference' # 'inference', 'data'
  verbose: False
  num_graders: 1
  use_multi_agents: False
  print_every: 50
  output_response_filename: 'outputs/response'
  save_output_response: True