datasets:
  data_dir: 'data'
  file_name: 'linda_problems.json'
  test_on_subset: True # for debugging only
  num_test_data: 10
  num_synthetic_examples: 1
  synthetic_data_filename: 'data/synthetic_dataset.json'
  occupations_filename: 'data/occupations_data.txt'
  fallacy_type: 'linda'
  generate_mode: 'baseline' # 'baseline', 'gold', 'random'
models:
  llm_model: 'gpt-3.5-turbo'  # 'gpt-3.5-turbo', 'gpt-4-turbo-preview'
inference:
  task: 'inference' # 'inference', 'data'
  verbose: False
  num_graders: 1
  use_multi_agents: False
  print_every: 50
  output_response_filename: 'outputs/response'
  save_output_response: True